"""Initial schema with all tables

Revision ID: ef041ce476ce
Revises: 
Create Date: 2025-10-24 00:17:31.814194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef041ce476ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Coin symbol (uppercase, unique)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full coin name'),
    sa.Column('coin_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Coin-specific metadata (contract address, network, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was inserted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_symbol'), 'coin', ['symbol'], unique=True)
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Exchange name (lowercase, unique)'),
    sa.Column('ccxt_id', sa.String(length=50), nullable=True, comment='CCXT exchange identifier (null for custom integrations)'),
    sa.Column('is_ccxt_supported', sa.Boolean(), nullable=False, comment='Whether this exchange is supported by CCXT'),
    sa.Column('custom_integration_class', sa.Text(), nullable=True, comment="Python path to custom collector class (e.g., 'src.collectors.custom.MyCollector')"),
    sa.Column('exchange_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Exchange-specific metadata (rate limits, capabilities, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_name'), 'exchange', ['name'], unique=True)
    op.create_table('listing_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Trading type (lowercase, unique)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of the listing type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_type_type'), 'listing_type', ['type'], unique=True)
    op.create_table('listing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False, comment='Foreign key to Exchange'),
    sa.Column('coin_id', sa.Integer(), nullable=False, comment='Foreign key to Coin'),
    sa.Column('listing_type_id', sa.Integer(), nullable=False, comment='Foreign key to ListingType'),
    sa.Column('ccxt_symbol', sa.String(length=50), nullable=False, comment="CCXT symbol format (e.g., 'BTC/USDT:USDT')"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether data collection is active'),
    sa.Column('backfill_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='backfillstatus', native_enum=False), nullable=False, comment='Historical data backfill status'),
    sa.Column('backfill_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Backfill progress details (last_timestamp, total_candles, errors, etc.)'),
    sa.Column('collector_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Collector configuration (intervals, data types, polling frequency)'),
    sa.Column('listing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Exchange-provided metadata (leverage, decimals, min_size, etc.)'),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when data collection was activated'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_type_id'], ['listing_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'coin_id', 'listing_type_id', name='uq_exchange_coin_type')
    )
    op.create_index('idx_listing_active', 'listing', ['is_active'], unique=False)
    op.create_index('idx_listing_backfill_status', 'listing', ['backfill_status'], unique=False)
    op.create_index(op.f('ix_listing_coin_id'), 'listing', ['coin_id'], unique=False)
    op.create_index(op.f('ix_listing_exchange_id'), 'listing', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_listing_is_active'), 'listing', ['is_active'], unique=False)
    op.create_index(op.f('ix_listing_listing_type_id'), 'listing', ['listing_type_id'], unique=False)
    op.create_table('candle',
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Foreign key to Listing'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Candle timestamp (partition key)'),
    sa.Column('interval', sa.String(length=10), nullable=False, comment='Candle interval (1m, 5m, 15m, 1h, 4h, 1d)'),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False, comment='Opening price'),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False, comment='Highest price'),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False, comment='Lowest price'),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False, comment='Closing price'),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False, comment='Trading volume'),
    sa.Column('trades_count', sa.Integer(), nullable=True, comment='Number of trades in this candle (if available)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was inserted'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'timestamp', 'interval')
    )
    op.create_index('idx_candle_listing_interval_time', 'candle', ['listing_id', 'interval', 'timestamp'], unique=False)
    op.create_table('funding_rate',
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Foreign key to Listing'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Funding rate timestamp (partition key)'),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False, comment='Funding rate (as decimal)'),
    sa.Column('predicted_rate', sa.Numeric(precision=20, scale=10), nullable=True, comment='Predicted next funding rate'),
    sa.Column('mark_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Mark price at this timestamp'),
    sa.Column('index_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Index/oracle price at this timestamp'),
    sa.Column('premium', sa.Numeric(precision=20, scale=8), nullable=True, comment='Premium (mark_price - index_price)'),
    sa.Column('next_funding_time', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of next funding payment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was inserted'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'timestamp')
    )
    op.create_index('idx_funding_rate_listing_time', 'funding_rate', ['listing_id', 'timestamp'], unique=False)
    op.create_table('market_metadata',
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Foreign key to Listing'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Snapshot timestamp (partition key)'),
    sa.Column('bid', sa.Numeric(precision=20, scale=8), nullable=True, comment='Best bid price'),
    sa.Column('ask', sa.Numeric(precision=20, scale=8), nullable=True, comment='Best ask price'),
    sa.Column('last_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Last traded price'),
    sa.Column('volume_24h', sa.Numeric(precision=30, scale=8), nullable=True, comment='24-hour trading volume (base currency)'),
    sa.Column('volume_quote_24h', sa.Numeric(precision=30, scale=2), nullable=True, comment='24-hour trading volume (quote currency/USD)'),
    sa.Column('price_change_24h', sa.Numeric(precision=20, scale=8), nullable=True, comment='24-hour price change (absolute)'),
    sa.Column('percentage_change_24h', sa.Numeric(precision=10, scale=4), nullable=True, comment='24-hour percentage change'),
    sa.Column('high_24h', sa.Numeric(precision=20, scale=8), nullable=True, comment='24-hour high price'),
    sa.Column('low_24h', sa.Numeric(precision=20, scale=8), nullable=True, comment='24-hour low price'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional exchange-specific fields'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was inserted'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'timestamp')
    )
    op.create_index('idx_market_metadata_listing_time', 'market_metadata', ['listing_id', 'timestamp'], unique=False)
    op.create_table('open_interest',
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Foreign key to Listing'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Open interest timestamp (partition key)'),
    sa.Column('open_interest', sa.Numeric(precision=30, scale=8), nullable=False, comment='Open interest in contracts/coins'),
    sa.Column('open_interest_value', sa.Numeric(precision=30, scale=2), nullable=True, comment='Open interest value in USD'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was inserted'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'timestamp')
    )
    op.create_index('idx_open_interest_listing_time', 'open_interest', ['listing_id', 'timestamp'], unique=False)
    op.create_table('trade',
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Foreign key to Listing'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Trade timestamp (partition key)'),
    sa.Column('trade_id', sa.String(length=100), nullable=False, comment='Exchange-specific trade ID'),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False, comment='Trade price'),
    sa.Column('amount', sa.Numeric(precision=30, scale=8), nullable=False, comment='Trade amount'),
    sa.Column('side', sa.String(length=10), nullable=False, comment='Trade side (buy or sell)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was inserted'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'timestamp', 'trade_id')
    )
    op.create_index('idx_trade_listing_time', 'trade', ['listing_id', 'timestamp'], unique=False)

    # Convert time-series tables to TimescaleDB hypertables
    # Note: This requires TimescaleDB extension to be enabled
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")

    # Candle table - partition by timestamp (time dimension)
    # chunk_time_interval: 7 days of data per chunk
    op.execute("""
        SELECT create_hypertable(
            'candle',
            'timestamp',
            chunk_time_interval => INTERVAL '7 days',
            if_not_exists => TRUE
        );
    """)

    # Funding rate table - partition by timestamp
    # chunk_time_interval: 30 days (funding rates change less frequently)
    op.execute("""
        SELECT create_hypertable(
            'funding_rate',
            'timestamp',
            chunk_time_interval => INTERVAL '30 days',
            if_not_exists => TRUE
        );
    """)

    # Open interest table - partition by timestamp
    # chunk_time_interval: 7 days
    op.execute("""
        SELECT create_hypertable(
            'open_interest',
            'timestamp',
            chunk_time_interval => INTERVAL '7 days',
            if_not_exists => TRUE
        );
    """)

    # Market metadata (ticker) table - partition by timestamp
    # chunk_time_interval: 7 days
    op.execute("""
        SELECT create_hypertable(
            'market_metadata',
            'timestamp',
            chunk_time_interval => INTERVAL '7 days',
            if_not_exists => TRUE
        );
    """)

    # Trade table - partition by timestamp
    # chunk_time_interval: 1 day (trades are high volume)
    op.execute("""
        SELECT create_hypertable(
            'trade',
            'timestamp',
            chunk_time_interval => INTERVAL '1 day',
            if_not_exists => TRUE
        );
    """)

    # Enable compression on time-series tables to save disk space
    # Compress data older than 7 days
    op.execute("""
        ALTER TABLE candle SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'listing_id,interval'
        );
    """)
    op.execute("""
        SELECT add_compression_policy('candle', INTERVAL '7 days');
    """)

    op.execute("""
        ALTER TABLE funding_rate SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'listing_id'
        );
    """)
    op.execute("""
        SELECT add_compression_policy('funding_rate', INTERVAL '30 days');
    """)

    op.execute("""
        ALTER TABLE open_interest SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'listing_id'
        );
    """)
    op.execute("""
        SELECT add_compression_policy('open_interest', INTERVAL '7 days');
    """)

    op.execute("""
        ALTER TABLE market_metadata SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'listing_id'
        );
    """)
    op.execute("""
        SELECT add_compression_policy('market_metadata', INTERVAL '7 days');
    """)

    op.execute("""
        ALTER TABLE trade SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'listing_id'
        );
    """)
    op.execute("""
        SELECT add_compression_policy('trade', INTERVAL '3 days');
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trade_listing_time', table_name='trade')
    op.drop_table('trade')
    op.drop_index('idx_open_interest_listing_time', table_name='open_interest')
    op.drop_table('open_interest')
    op.drop_index('idx_market_metadata_listing_time', table_name='market_metadata')
    op.drop_table('market_metadata')
    op.drop_index('idx_funding_rate_listing_time', table_name='funding_rate')
    op.drop_table('funding_rate')
    op.drop_index('idx_candle_listing_interval_time', table_name='candle')
    op.drop_table('candle')
    op.drop_index(op.f('ix_listing_listing_type_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_is_active'), table_name='listing')
    op.drop_index(op.f('ix_listing_exchange_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_coin_id'), table_name='listing')
    op.drop_index('idx_listing_backfill_status', table_name='listing')
    op.drop_index('idx_listing_active', table_name='listing')
    op.drop_table('listing')
    op.drop_index(op.f('ix_listing_type_type'), table_name='listing_type')
    op.drop_table('listing_type')
    op.drop_index(op.f('ix_exchange_name'), table_name='exchange')
    op.drop_table('exchange')
    op.drop_index(op.f('ix_coin_symbol'), table_name='coin')
    op.drop_table('coin')
    # ### end Alembic commands ###
