# Kirby Starlistings Configuration
# Define which exchange + trading pair (coin/quote) + market type + intervals to collect data for

version: "1.1"

# Exchange definitions
exchanges:
  - name: hyperliquid
    display_name: Hyperliquid
    active: true

# Coin definitions (base assets)
coins:
  - symbol: BTC
    name: Bitcoin
    active: true
  - symbol: SOL
    name: Solana
    active: true

# Quote currency definitions
quote_currencies:
  - symbol: USD
    name: US Dollar
    active: true
  - symbol: USDC
    name: USD Coin
    active: true

# Market type definitions
market_types:
  - name: perps
    display_name: Perpetuals
    active: true
  - name: spot
    display_name: Spot
    active: true

# Starlistings - combinations of exchange + coin + quote + market_type + intervals
# Trading pair = coin/quote (e.g., BTC/USD, SOL/USDC)
starlistings:
  # Hyperliquid BTC/USD Perpetuals
  - exchange: hyperliquid
    coin: BTC
    quote: USD
    market_type: perps
    intervals:
      - 1m
      - 15m
      - 4h
      - 1d
    active: true

  # Hyperliquid SOL/USD Perpetuals
  - exchange: hyperliquid
    coin: SOL
    quote: USD
    market_type: perps
    intervals:
      - 1m
      - 15m
      - 4h
      - 1d
    active: true
